default_language_version:
  python: python3.7

repos:
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v1.0.1
    hooks:
      - id: docker-compose-check
  - repo: https://github.com/MartinThoma/check-pip-compile
    rev: 0.1.0
    hooks:
      - id: check-pip-compile
        files: ^requirements\.(in|txt)$
        args: [requirements.in]
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --apply
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
